//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace EasyBrailleEdit {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("AppOptions")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class AppOptions : global::System.Data.DataSet {
        
        private MainDataTable tableMain;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public AppOptions() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected AppOptions(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["Main"] != null)) {
                    base.Tables.Add(new MainDataTable(ds.Tables["Main"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MainDataTable Main {
            get {
                return this.tableMain;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            AppOptions cln = ((AppOptions)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Main"] != null)) {
                    base.Tables.Add(new MainDataTable(ds.Tables["Main"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableMain = ((MainDataTable)(base.Tables["Main"]));
            if ((initTable == true)) {
                if ((this.tableMain != null)) {
                    this.tableMain.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "AppOptions";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/AppOtions.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableMain = new MainDataTable();
            base.Tables.Add(this.tableMain);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeMain() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            AppOptions ds = new AppOptions();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void MainRowChangeEventHandler(object sender, MainRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class MainDataTable : global::System.Data.TypedTableBase<MainRow> {
            
            private global::System.Data.DataColumn columnCellsPerLine;
            
            private global::System.Data.DataColumn columnDefaultTextPrinter;
            
            private global::System.Data.DataColumn columnLinesPerPage;
            
            private global::System.Data.DataColumn columnErrorProneWords;
            
            private global::System.Data.DataColumn columnPrintBrailleToBrailler;
            
            private global::System.Data.DataColumn columnPrintBrailleToFile;
            
            private global::System.Data.DataColumn columnPrintBrailleToFileName;
            
            private global::System.Data.DataColumn columnPrintBrailleUseNewLineForPageBreak;
            
            private global::System.Data.DataColumn columnPrintBrailleSendPageBreakAtEndOfDoc;
            
            private global::System.Data.DataColumn columnBraillePrinterPort;
            
            private global::System.Data.DataColumn columnPrintTextMarginLeft;
            
            private global::System.Data.DataColumn columnPrintTextMarginTop;
            
            private global::System.Data.DataColumn columnPrintTextFontSize;
            
            private global::System.Data.DataColumn columnPrintTextLineHeight;
            
            private global::System.Data.DataColumn columnPrintTextFontName;
            
            private global::System.Data.DataColumn columnPhraseFiles;
            
            private global::System.Data.DataColumn columnPrintPageFoot;
            
            private global::System.Data.DataColumn columnPrintTextMarginRight;
            
            private global::System.Data.DataColumn columnPrintTextMarginBottom;
            
            private global::System.Data.DataColumn columnPrintTextMarginLeft2;
            
            private global::System.Data.DataColumn columnPrintTextMarginTop2;
            
            private global::System.Data.DataColumn columnPrintTextMarginRight2;
            
            private global::System.Data.DataColumn columnPrintTextMarginBottom2;
            
            private global::System.Data.DataColumn columnPrintTextPaperSourceName;
            
            private global::System.Data.DataColumn columnPrintTextPaperName;
            
            private global::System.Data.DataColumn columnBraillePrinterName;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MainDataTable() {
                this.TableName = "Main";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal MainDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected MainDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CellsPerLineColumn {
                get {
                    return this.columnCellsPerLine;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DefaultTextPrinterColumn {
                get {
                    return this.columnDefaultTextPrinter;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn LinesPerPageColumn {
                get {
                    return this.columnLinesPerPage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ErrorProneWordsColumn {
                get {
                    return this.columnErrorProneWords;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintBrailleToBraillerColumn {
                get {
                    return this.columnPrintBrailleToBrailler;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintBrailleToFileColumn {
                get {
                    return this.columnPrintBrailleToFile;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintBrailleToFileNameColumn {
                get {
                    return this.columnPrintBrailleToFileName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintBrailleUseNewLineForPageBreakColumn {
                get {
                    return this.columnPrintBrailleUseNewLineForPageBreak;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintBrailleSendPageBreakAtEndOfDocColumn {
                get {
                    return this.columnPrintBrailleSendPageBreakAtEndOfDoc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BraillePrinterPortColumn {
                get {
                    return this.columnBraillePrinterPort;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginLeftColumn {
                get {
                    return this.columnPrintTextMarginLeft;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginTopColumn {
                get {
                    return this.columnPrintTextMarginTop;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextFontSizeColumn {
                get {
                    return this.columnPrintTextFontSize;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextLineHeightColumn {
                get {
                    return this.columnPrintTextLineHeight;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextFontNameColumn {
                get {
                    return this.columnPrintTextFontName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PhraseFilesColumn {
                get {
                    return this.columnPhraseFiles;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintPageFootColumn {
                get {
                    return this.columnPrintPageFoot;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginRightColumn {
                get {
                    return this.columnPrintTextMarginRight;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginBottomColumn {
                get {
                    return this.columnPrintTextMarginBottom;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginLeft2Column {
                get {
                    return this.columnPrintTextMarginLeft2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginTop2Column {
                get {
                    return this.columnPrintTextMarginTop2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginRight2Column {
                get {
                    return this.columnPrintTextMarginRight2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextMarginBottom2Column {
                get {
                    return this.columnPrintTextMarginBottom2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextPaperSourceNameColumn {
                get {
                    return this.columnPrintTextPaperSourceName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PrintTextPaperNameColumn {
                get {
                    return this.columnPrintTextPaperName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BraillePrinterNameColumn {
                get {
                    return this.columnBraillePrinterName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MainRow this[int index] {
                get {
                    return ((MainRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MainRowChangeEventHandler MainRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MainRowChangeEventHandler MainRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MainRowChangeEventHandler MainRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MainRowChangeEventHandler MainRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddMainRow(MainRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MainRow AddMainRow(
                        int CellsPerLine, 
                        string DefaultTextPrinter, 
                        int LinesPerPage, 
                        string ErrorProneWords, 
                        bool PrintBrailleToBrailler, 
                        bool PrintBrailleToFile, 
                        string PrintBrailleToFileName, 
                        bool PrintBrailleUseNewLineForPageBreak, 
                        bool PrintBrailleSendPageBreakAtEndOfDoc, 
                        string BraillePrinterPort, 
                        int PrintTextMarginLeft, 
                        int PrintTextMarginTop, 
                        double PrintTextFontSize, 
                        double PrintTextLineHeight, 
                        string PrintTextFontName, 
                        string PhraseFiles, 
                        bool PrintPageFoot, 
                        int PrintTextMarginRight, 
                        int PrintTextMarginBottom, 
                        int PrintTextMarginLeft2, 
                        int PrintTextMarginTop2, 
                        int PrintTextMarginRight2, 
                        int PrintTextMarginBottom2, 
                        string PrintTextPaperSourceName, 
                        string PrintTextPaperName, 
                        string BraillePrinterName) {
                MainRow rowMainRow = ((MainRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CellsPerLine,
                        DefaultTextPrinter,
                        LinesPerPage,
                        ErrorProneWords,
                        PrintBrailleToBrailler,
                        PrintBrailleToFile,
                        PrintBrailleToFileName,
                        PrintBrailleUseNewLineForPageBreak,
                        PrintBrailleSendPageBreakAtEndOfDoc,
                        BraillePrinterPort,
                        PrintTextMarginLeft,
                        PrintTextMarginTop,
                        PrintTextFontSize,
                        PrintTextLineHeight,
                        PrintTextFontName,
                        PhraseFiles,
                        PrintPageFoot,
                        PrintTextMarginRight,
                        PrintTextMarginBottom,
                        PrintTextMarginLeft2,
                        PrintTextMarginTop2,
                        PrintTextMarginRight2,
                        PrintTextMarginBottom2,
                        PrintTextPaperSourceName,
                        PrintTextPaperName,
                        BraillePrinterName};
                rowMainRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowMainRow);
                return rowMainRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                MainDataTable cln = ((MainDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new MainDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnCellsPerLine = base.Columns["CellsPerLine"];
                this.columnDefaultTextPrinter = base.Columns["DefaultTextPrinter"];
                this.columnLinesPerPage = base.Columns["LinesPerPage"];
                this.columnErrorProneWords = base.Columns["ErrorProneWords"];
                this.columnPrintBrailleToBrailler = base.Columns["PrintBrailleToBrailler"];
                this.columnPrintBrailleToFile = base.Columns["PrintBrailleToFile"];
                this.columnPrintBrailleToFileName = base.Columns["PrintBrailleToFileName"];
                this.columnPrintBrailleUseNewLineForPageBreak = base.Columns["PrintBrailleUseNewLineForPageBreak"];
                this.columnPrintBrailleSendPageBreakAtEndOfDoc = base.Columns["PrintBrailleSendPageBreakAtEndOfDoc"];
                this.columnBraillePrinterPort = base.Columns["BraillePrinterPort"];
                this.columnPrintTextMarginLeft = base.Columns["PrintTextMarginLeft"];
                this.columnPrintTextMarginTop = base.Columns["PrintTextMarginTop"];
                this.columnPrintTextFontSize = base.Columns["PrintTextFontSize"];
                this.columnPrintTextLineHeight = base.Columns["PrintTextLineHeight"];
                this.columnPrintTextFontName = base.Columns["PrintTextFontName"];
                this.columnPhraseFiles = base.Columns["PhraseFiles"];
                this.columnPrintPageFoot = base.Columns["PrintPageFoot"];
                this.columnPrintTextMarginRight = base.Columns["PrintTextMarginRight"];
                this.columnPrintTextMarginBottom = base.Columns["PrintTextMarginBottom"];
                this.columnPrintTextMarginLeft2 = base.Columns["PrintTextMarginLeft2"];
                this.columnPrintTextMarginTop2 = base.Columns["PrintTextMarginTop2"];
                this.columnPrintTextMarginRight2 = base.Columns["PrintTextMarginRight2"];
                this.columnPrintTextMarginBottom2 = base.Columns["PrintTextMarginBottom2"];
                this.columnPrintTextPaperSourceName = base.Columns["PrintTextPaperSourceName"];
                this.columnPrintTextPaperName = base.Columns["PrintTextPaperName"];
                this.columnBraillePrinterName = base.Columns["BraillePrinterName"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnCellsPerLine = new global::System.Data.DataColumn("CellsPerLine", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCellsPerLine);
                this.columnDefaultTextPrinter = new global::System.Data.DataColumn("DefaultTextPrinter", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDefaultTextPrinter);
                this.columnLinesPerPage = new global::System.Data.DataColumn("LinesPerPage", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLinesPerPage);
                this.columnErrorProneWords = new global::System.Data.DataColumn("ErrorProneWords", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnErrorProneWords);
                this.columnPrintBrailleToBrailler = new global::System.Data.DataColumn("PrintBrailleToBrailler", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintBrailleToBrailler);
                this.columnPrintBrailleToFile = new global::System.Data.DataColumn("PrintBrailleToFile", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintBrailleToFile);
                this.columnPrintBrailleToFileName = new global::System.Data.DataColumn("PrintBrailleToFileName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintBrailleToFileName);
                this.columnPrintBrailleUseNewLineForPageBreak = new global::System.Data.DataColumn("PrintBrailleUseNewLineForPageBreak", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintBrailleUseNewLineForPageBreak);
                this.columnPrintBrailleSendPageBreakAtEndOfDoc = new global::System.Data.DataColumn("PrintBrailleSendPageBreakAtEndOfDoc", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintBrailleSendPageBreakAtEndOfDoc);
                this.columnBraillePrinterPort = new global::System.Data.DataColumn("BraillePrinterPort", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBraillePrinterPort);
                this.columnPrintTextMarginLeft = new global::System.Data.DataColumn("PrintTextMarginLeft", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginLeft);
                this.columnPrintTextMarginTop = new global::System.Data.DataColumn("PrintTextMarginTop", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginTop);
                this.columnPrintTextFontSize = new global::System.Data.DataColumn("PrintTextFontSize", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextFontSize);
                this.columnPrintTextLineHeight = new global::System.Data.DataColumn("PrintTextLineHeight", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextLineHeight);
                this.columnPrintTextFontName = new global::System.Data.DataColumn("PrintTextFontName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextFontName);
                this.columnPhraseFiles = new global::System.Data.DataColumn("PhraseFiles", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPhraseFiles);
                this.columnPrintPageFoot = new global::System.Data.DataColumn("PrintPageFoot", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintPageFoot);
                this.columnPrintTextMarginRight = new global::System.Data.DataColumn("PrintTextMarginRight", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginRight);
                this.columnPrintTextMarginBottom = new global::System.Data.DataColumn("PrintTextMarginBottom", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginBottom);
                this.columnPrintTextMarginLeft2 = new global::System.Data.DataColumn("PrintTextMarginLeft2", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginLeft2);
                this.columnPrintTextMarginTop2 = new global::System.Data.DataColumn("PrintTextMarginTop2", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginTop2);
                this.columnPrintTextMarginRight2 = new global::System.Data.DataColumn("PrintTextMarginRight2", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginRight2);
                this.columnPrintTextMarginBottom2 = new global::System.Data.DataColumn("PrintTextMarginBottom2", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextMarginBottom2);
                this.columnPrintTextPaperSourceName = new global::System.Data.DataColumn("PrintTextPaperSourceName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextPaperSourceName);
                this.columnPrintTextPaperName = new global::System.Data.DataColumn("PrintTextPaperName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrintTextPaperName);
                this.columnBraillePrinterName = new global::System.Data.DataColumn("BraillePrinterName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBraillePrinterName);
                this.columnCellsPerLine.DefaultValue = ((int)(40));
                this.columnLinesPerPage.DefaultValue = ((int)(26));
                this.columnErrorProneWords.DefaultValue = ((string)("為"));
                this.columnPrintBrailleToBrailler.DefaultValue = ((bool)(true));
                this.columnPrintBrailleToFile.DefaultValue = ((bool)(false));
                this.columnPrintBrailleUseNewLineForPageBreak.DefaultValue = ((bool)(false));
                this.columnPrintBrailleSendPageBreakAtEndOfDoc.DefaultValue = ((bool)(false));
                this.columnBraillePrinterPort.DefaultValue = ((string)("LPT1"));
                this.columnPrintTextMarginLeft.DefaultValue = ((int)(105));
                this.columnPrintTextMarginTop.DefaultValue = ((int)(12));
                this.columnPrintTextFontSize.DefaultValue = ((double)(12D));
                this.columnPrintTextLineHeight.DefaultValue = ((double)(40.0975D));
                this.columnPrintTextFontName.DefaultValue = ((string)("新細明體"));
                this.columnPrintPageFoot.DefaultValue = ((bool)(true));
                this.columnPrintTextMarginRight.DefaultValue = ((int)(150));
                this.columnPrintTextMarginBottom.DefaultValue = ((int)(100));
                this.columnPrintTextMarginLeft2.DefaultValue = ((int)(105));
                this.columnPrintTextMarginTop2.DefaultValue = ((int)(15));
                this.columnPrintTextMarginRight2.DefaultValue = ((int)(150));
                this.columnPrintTextMarginBottom2.DefaultValue = ((int)(100));
                this.columnPrintTextPaperSourceName.DefaultValue = ((string)(""));
                this.columnPrintTextPaperName.DefaultValue = ((string)(""));
                this.columnBraillePrinterName.DefaultValue = ((string)(""));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MainRow NewMainRow() {
                return ((MainRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new MainRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(MainRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MainRowChanged != null)) {
                    this.MainRowChanged(this, new MainRowChangeEvent(((MainRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MainRowChanging != null)) {
                    this.MainRowChanging(this, new MainRowChangeEvent(((MainRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MainRowDeleted != null)) {
                    this.MainRowDeleted(this, new MainRowChangeEvent(((MainRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MainRowDeleting != null)) {
                    this.MainRowDeleting(this, new MainRowChangeEvent(((MainRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveMainRow(MainRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                AppOptions ds = new AppOptions();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "MainDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class MainRow : global::System.Data.DataRow {
            
            private MainDataTable tableMain;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal MainRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableMain = ((MainDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int CellsPerLine {
                get {
                    try {
                        return ((int)(this[this.tableMain.CellsPerLineColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CellsPerLine\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.CellsPerLineColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DefaultTextPrinter {
                get {
                    try {
                        return ((string)(this[this.tableMain.DefaultTextPrinterColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DefaultTextPrinter\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.DefaultTextPrinterColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int LinesPerPage {
                get {
                    try {
                        return ((int)(this[this.tableMain.LinesPerPageColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LinesPerPage\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.LinesPerPageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ErrorProneWords {
                get {
                    try {
                        return ((string)(this[this.tableMain.ErrorProneWordsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ErrorProneWords\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.ErrorProneWordsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool PrintBrailleToBrailler {
                get {
                    try {
                        return ((bool)(this[this.tableMain.PrintBrailleToBraillerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintBrailleToBrailler\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintBrailleToBraillerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool PrintBrailleToFile {
                get {
                    try {
                        return ((bool)(this[this.tableMain.PrintBrailleToFileColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintBrailleToFile\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintBrailleToFileColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PrintBrailleToFileName {
                get {
                    try {
                        return ((string)(this[this.tableMain.PrintBrailleToFileNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintBrailleToFileName\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintBrailleToFileNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool PrintBrailleUseNewLineForPageBreak {
                get {
                    try {
                        return ((bool)(this[this.tableMain.PrintBrailleUseNewLineForPageBreakColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintBrailleUseNewLineForPageBreak\' in table \'Main\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintBrailleUseNewLineForPageBreakColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool PrintBrailleSendPageBreakAtEndOfDoc {
                get {
                    try {
                        return ((bool)(this[this.tableMain.PrintBrailleSendPageBreakAtEndOfDocColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintBrailleSendPageBreakAtEndOfDoc\' in table \'Main\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintBrailleSendPageBreakAtEndOfDocColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BraillePrinterPort {
                get {
                    try {
                        return ((string)(this[this.tableMain.BraillePrinterPortColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BraillePrinterPort\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.BraillePrinterPortColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginLeft {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginLeftColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginLeft\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginLeftColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginTop {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginTopColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginTop\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginTopColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double PrintTextFontSize {
                get {
                    try {
                        return ((double)(this[this.tableMain.PrintTextFontSizeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextFontSize\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextFontSizeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double PrintTextLineHeight {
                get {
                    try {
                        return ((double)(this[this.tableMain.PrintTextLineHeightColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextLineHeight\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextLineHeightColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PrintTextFontName {
                get {
                    try {
                        return ((string)(this[this.tableMain.PrintTextFontNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextFontName\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextFontNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PhraseFiles {
                get {
                    try {
                        return ((string)(this[this.tableMain.PhraseFilesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PhraseFiles\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PhraseFilesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool PrintPageFoot {
                get {
                    try {
                        return ((bool)(this[this.tableMain.PrintPageFootColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintPageFoot\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintPageFootColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginRight {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginRightColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginRight\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginRightColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginBottom {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginBottomColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginBottom\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginBottomColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginLeft2 {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginLeft2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginLeft2\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginLeft2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginTop2 {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginTop2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginTop2\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginTop2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginRight2 {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginRight2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginRight2\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginRight2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int PrintTextMarginBottom2 {
                get {
                    try {
                        return ((int)(this[this.tableMain.PrintTextMarginBottom2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextMarginBottom2\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextMarginBottom2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PrintTextPaperSourceName {
                get {
                    try {
                        return ((string)(this[this.tableMain.PrintTextPaperSourceNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextPaperSourceName\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextPaperSourceNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PrintTextPaperName {
                get {
                    try {
                        return ((string)(this[this.tableMain.PrintTextPaperNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PrintTextPaperName\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.PrintTextPaperNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BraillePrinterName {
                get {
                    try {
                        return ((string)(this[this.tableMain.BraillePrinterNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BraillePrinterName\' in table \'Main\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMain.BraillePrinterNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCellsPerLineNull() {
                return this.IsNull(this.tableMain.CellsPerLineColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCellsPerLineNull() {
                this[this.tableMain.CellsPerLineColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDefaultTextPrinterNull() {
                return this.IsNull(this.tableMain.DefaultTextPrinterColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDefaultTextPrinterNull() {
                this[this.tableMain.DefaultTextPrinterColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsLinesPerPageNull() {
                return this.IsNull(this.tableMain.LinesPerPageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetLinesPerPageNull() {
                this[this.tableMain.LinesPerPageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsErrorProneWordsNull() {
                return this.IsNull(this.tableMain.ErrorProneWordsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetErrorProneWordsNull() {
                this[this.tableMain.ErrorProneWordsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintBrailleToBraillerNull() {
                return this.IsNull(this.tableMain.PrintBrailleToBraillerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintBrailleToBraillerNull() {
                this[this.tableMain.PrintBrailleToBraillerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintBrailleToFileNull() {
                return this.IsNull(this.tableMain.PrintBrailleToFileColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintBrailleToFileNull() {
                this[this.tableMain.PrintBrailleToFileColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintBrailleToFileNameNull() {
                return this.IsNull(this.tableMain.PrintBrailleToFileNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintBrailleToFileNameNull() {
                this[this.tableMain.PrintBrailleToFileNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintBrailleUseNewLineForPageBreakNull() {
                return this.IsNull(this.tableMain.PrintBrailleUseNewLineForPageBreakColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintBrailleUseNewLineForPageBreakNull() {
                this[this.tableMain.PrintBrailleUseNewLineForPageBreakColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintBrailleSendPageBreakAtEndOfDocNull() {
                return this.IsNull(this.tableMain.PrintBrailleSendPageBreakAtEndOfDocColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintBrailleSendPageBreakAtEndOfDocNull() {
                this[this.tableMain.PrintBrailleSendPageBreakAtEndOfDocColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBraillePrinterPortNull() {
                return this.IsNull(this.tableMain.BraillePrinterPortColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBraillePrinterPortNull() {
                this[this.tableMain.BraillePrinterPortColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginLeftNull() {
                return this.IsNull(this.tableMain.PrintTextMarginLeftColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginLeftNull() {
                this[this.tableMain.PrintTextMarginLeftColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginTopNull() {
                return this.IsNull(this.tableMain.PrintTextMarginTopColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginTopNull() {
                this[this.tableMain.PrintTextMarginTopColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextFontSizeNull() {
                return this.IsNull(this.tableMain.PrintTextFontSizeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextFontSizeNull() {
                this[this.tableMain.PrintTextFontSizeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextLineHeightNull() {
                return this.IsNull(this.tableMain.PrintTextLineHeightColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextLineHeightNull() {
                this[this.tableMain.PrintTextLineHeightColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextFontNameNull() {
                return this.IsNull(this.tableMain.PrintTextFontNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextFontNameNull() {
                this[this.tableMain.PrintTextFontNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPhraseFilesNull() {
                return this.IsNull(this.tableMain.PhraseFilesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPhraseFilesNull() {
                this[this.tableMain.PhraseFilesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintPageFootNull() {
                return this.IsNull(this.tableMain.PrintPageFootColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintPageFootNull() {
                this[this.tableMain.PrintPageFootColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginRightNull() {
                return this.IsNull(this.tableMain.PrintTextMarginRightColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginRightNull() {
                this[this.tableMain.PrintTextMarginRightColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginBottomNull() {
                return this.IsNull(this.tableMain.PrintTextMarginBottomColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginBottomNull() {
                this[this.tableMain.PrintTextMarginBottomColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginLeft2Null() {
                return this.IsNull(this.tableMain.PrintTextMarginLeft2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginLeft2Null() {
                this[this.tableMain.PrintTextMarginLeft2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginTop2Null() {
                return this.IsNull(this.tableMain.PrintTextMarginTop2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginTop2Null() {
                this[this.tableMain.PrintTextMarginTop2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginRight2Null() {
                return this.IsNull(this.tableMain.PrintTextMarginRight2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginRight2Null() {
                this[this.tableMain.PrintTextMarginRight2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextMarginBottom2Null() {
                return this.IsNull(this.tableMain.PrintTextMarginBottom2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextMarginBottom2Null() {
                this[this.tableMain.PrintTextMarginBottom2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextPaperSourceNameNull() {
                return this.IsNull(this.tableMain.PrintTextPaperSourceNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextPaperSourceNameNull() {
                this[this.tableMain.PrintTextPaperSourceNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPrintTextPaperNameNull() {
                return this.IsNull(this.tableMain.PrintTextPaperNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPrintTextPaperNameNull() {
                this[this.tableMain.PrintTextPaperNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBraillePrinterNameNull() {
                return this.IsNull(this.tableMain.BraillePrinterNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBraillePrinterNameNull() {
                this[this.tableMain.BraillePrinterNameColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class MainRowChangeEvent : global::System.EventArgs {
            
            private MainRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MainRowChangeEvent(MainRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MainRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591